config/routes.rb
Rails.application.routes.draw do

  resources :entries, only: [:new, :create, :destroy]
  root 'entries#new'

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  validates :name, :message, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def new
    @entries = Entry.order(created_at: :desc)
    @entry = Entry.new
  end

  def create
    @entry = Entry.new(entry_params)
    if @entry.save
      flash[:success] = 'The entry was created succesfully'
      redirect_to root_path
    else
      @entries = Entry.order(created_at: :desc)
      render :new
    end
  end

  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy
    flash[:success] = 'The entry was deleted succesfully'
    redirect_to root_path
  end

  private

  def entry_params
    params.require(:entry).permit(:name, :message)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/entries/new.html.erb
<% flash.each do |key, value| %>
  <div class="flash-<%= key %>"><%= value %></div>
<% end %>

<% if @entry.errors.any? %>
  <% @entry.errors.full_messages.each do |msg| %>
    <div class="flash-error"><%= msg %></div>
  <% end %>
<% end %>

<%= form_for @entry do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :message %>
  <%= f.text_area :message, cols: 50, rows: 3 %>
  <%= f.submit 'Submit' %>
<% end %>

<hr>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Message</th>
      <th>Time Ago</th>
    </tr>
  </thead>
  <tbody>
    <% @entries.each do |entry| %>
      <tr>
        <td><%= entry.name %></td>
        <td><%= entry.message %></td>
        <td><%= time_ago_in_words(entry.created_at) %></td>
        <td><%= button_to "delete", entry_path(entry), method: :delete %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Guestbook</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>